# -*- coding: utf-8 -*-
"""Random&ImportaçãoDeBiblbioteca

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16H_nA0N0e9IK3nTToKk6n10AI5kWezMD
"""

#EXERCÍCIO 1

import random

x = random.randint(1,5)
print(x)

#EXERCÍCIO 2

import random

x = random.randint(1,10)
y = random.randint(1,10)
z = random.randint(1,10)

print(x,y,z)

#EXERCÍCIO 3

import random

random.randrange(10,30)